//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BundleChallenge) DeepCopyInto(out *BundleChallenge) {
	*out = *in
	out.Cloudflare = in.Cloudflare
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BundleChallenge.
func (in *BundleChallenge) DeepCopy() *BundleChallenge {
	if in == nil {
		return nil
	}
	out := new(BundleChallenge)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BundleCloudflare) DeepCopyInto(out *BundleCloudflare) {
	*out = *in
	in.APITokenSecretRef.DeepCopyInto(&out.APITokenSecretRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BundleCloudflare.
func (in *BundleCloudflare) DeepCopy() *BundleCloudflare {
	if in == nil {
		return nil
	}
	out := new(BundleCloudflare)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BundleIssuer) DeepCopyInto(out *BundleIssuer) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BundleIssuer.
func (in *BundleIssuer) DeepCopy() *BundleIssuer {
	if in == nil {
		return nil
	}
	out := new(BundleIssuer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BundleSecretTemplate) DeepCopyInto(out *BundleSecretTemplate) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BundleSecretTemplate.
func (in *BundleSecretTemplate) DeepCopy() *BundleSecretTemplate {
	if in == nil {
		return nil
	}
	out := new(BundleSecretTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateBundle) DeepCopyInto(out *CertificateBundle) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateBundle.
func (in *CertificateBundle) DeepCopy() *CertificateBundle {
	if in == nil {
		return nil
	}
	out := new(CertificateBundle)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CertificateBundle) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateBundleList) DeepCopyInto(out *CertificateBundleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CertificateBundle, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateBundleList.
func (in *CertificateBundleList) DeepCopy() *CertificateBundleList {
	if in == nil {
		return nil
	}
	out := new(CertificateBundleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CertificateBundleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateBundleSpec) DeepCopyInto(out *CertificateBundleSpec) {
	*out = *in
	if in.PublishedServiceSelector != nil {
		in, out := &in.PublishedServiceSelector, &out.PublishedServiceSelector
		*out = (*in).DeepCopy()
	}
	if in.AdditionalDomains != nil {
		in, out := &in.AdditionalDomains, &out.AdditionalDomains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Issuer = in.Issuer
	out.Challenge = in.Challenge
	out.SecretTemplate = in.SecretTemplate
	out.RenewBefore = in.RenewBefore
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateBundleSpec.
func (in *CertificateBundleSpec) DeepCopy() *CertificateBundleSpec {
	if in == nil {
		return nil
	}
	out := new(CertificateBundleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateBundleStatus) DeepCopyInto(out *CertificateBundleStatus) {
	*out = *in
	if in.EffectiveDomains != nil {
		in, out := &in.EffectiveDomains, &out.EffectiveDomains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CertificateSecretRef != nil {
		in, out := &in.CertificateSecretRef, &out.CertificateSecretRef
		*out = (*in).DeepCopy()
	}
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = (*in).DeepCopy()
	}
	if in.LastIssuedAt != nil {
		in, out := &in.LastIssuedAt, &out.LastIssuedAt
		*out = (*in).DeepCopy()
	}
	if in.NextAttemptAt != nil {
		in, out := &in.NextAttemptAt, &out.NextAttemptAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateBundleStatus.
func (in *CertificateBundleStatus) DeepCopy() *CertificateBundleStatus {
	if in == nil {
		return nil
	}
	out := new(CertificateBundleStatus)
	in.DeepCopyInto(out)
	return out
}
