//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TailnetBehavior) DeepCopyInto(out *TailnetBehavior) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TailnetBehavior.
func (in *TailnetBehavior) DeepCopy() *TailnetBehavior {
	if in == nil {
		return nil
	}
	out := new(TailnetBehavior)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TailnetDNSAuth) DeepCopyInto(out *TailnetDNSAuth) {
	*out = *in
	in.SecretRef.DeepCopyInto(&out.SecretRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TailnetDNSAuth.
func (in *TailnetDNSAuth) DeepCopy() *TailnetDNSAuth {
	if in == nil {
		return nil
	}
	out := new(TailnetDNSAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TailnetDNSConfig) DeepCopyInto(out *TailnetDNSConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TailnetDNSConfig.
func (in *TailnetDNSConfig) DeepCopy() *TailnetDNSConfig {
	if in == nil {
		return nil
	}
	out := new(TailnetDNSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TailnetDNSConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TailnetDNSConfigList) DeepCopyInto(out *TailnetDNSConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TailnetDNSConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TailnetDNSConfigList.
func (in *TailnetDNSConfigList) DeepCopy() *TailnetDNSConfigList {
	if in == nil {
		return nil
	}
	out := new(TailnetDNSConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TailnetDNSConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TailnetDNSConfigSpec) DeepCopyInto(out *TailnetDNSConfigSpec) {
	*out = *in
	in.Nameserver.DeepCopyInto(&out.Nameserver)
	out.Auth = in.Auth
	out.Behavior = in.Behavior
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TailnetDNSConfigSpec.
func (in *TailnetDNSConfigSpec) DeepCopy() *TailnetDNSConfigSpec {
	if in == nil {
		return nil
	}
	out := new(TailnetDNSConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TailnetDNSConfigStatus) DeepCopyInto(out *TailnetDNSConfigStatus) {
	*out = *in
	if in.LastAppliedAt != nil {
		in, out := &in.LastAppliedAt, &out.LastAppliedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TailnetDNSConfigStatus.
func (in *TailnetDNSConfigStatus) DeepCopy() *TailnetDNSConfigStatus {
	if in == nil {
		return nil
	}
	out := new(TailnetDNSConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TailnetDNSEndpoint) DeepCopyInto(out *TailnetDNSEndpoint) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TailnetDNSEndpoint.
func (in *TailnetDNSEndpoint) DeepCopy() *TailnetDNSEndpoint {
	if in == nil {
		return nil
	}
	out := new(TailnetDNSEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TailnetDNSEndpoint) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TailnetDNSEndpointAuth) DeepCopyInto(out *TailnetDNSEndpointAuth) {
	*out = *in
	in.SecretRef.DeepCopyInto(&out.SecretRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TailnetDNSEndpointAuth.
func (in *TailnetDNSEndpointAuth) DeepCopy() *TailnetDNSEndpointAuth {
	if in == nil {
		return nil
	}
	out := new(TailnetDNSEndpointAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TailnetDNSEndpointExposure) DeepCopyInto(out *TailnetDNSEndpointExposure) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TailnetDNSEndpointExposure.
func (in *TailnetDNSEndpointExposure) DeepCopy() *TailnetDNSEndpointExposure {
	if in == nil {
		return nil
	}
	out := new(TailnetDNSEndpointExposure)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TailnetDNSEndpointList) DeepCopyInto(out *TailnetDNSEndpointList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TailnetDNSEndpoint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TailnetDNSEndpointList.
func (in *TailnetDNSEndpointList) DeepCopy() *TailnetDNSEndpointList {
	if in == nil {
		return nil
	}
	out := new(TailnetDNSEndpointList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TailnetDNSEndpointList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TailnetDNSEndpointService) DeepCopyInto(out *TailnetDNSEndpointService) {
	*out = *in
	in.Ref.DeepCopyInto(&out.Ref)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TailnetDNSEndpointService.
func (in *TailnetDNSEndpointService) DeepCopy() *TailnetDNSEndpointService {
	if in == nil {
		return nil
	}
	out := new(TailnetDNSEndpointService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TailnetDNSEndpointSpec) DeepCopyInto(out *TailnetDNSEndpointSpec) {
	*out = *in
	out.Service = in.Service
	out.Auth = in.Auth
	out.Exposure = in.Exposure
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TailnetDNSEndpointSpec.
func (in *TailnetDNSEndpointSpec) DeepCopy() *TailnetDNSEndpointSpec {
	if in == nil {
		return nil
	}
	out := new(TailnetDNSEndpointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TailnetDNSEndpointStatus) DeepCopyInto(out *TailnetDNSEndpointStatus) {
	*out = *in
	if in.ResolvedServiceRef != nil {
		in, out := &in.ResolvedServiceRef, &out.ResolvedServiceRef
		*out = (*in).DeepCopy()
	}
	if in.ExposureServiceRef != nil {
		in, out := &in.ExposureServiceRef, &out.ExposureServiceRef
		*out = (*in).DeepCopy()
	}
	if in.LastAppliedAt != nil {
		in, out := &in.LastAppliedAt, &out.LastAppliedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TailnetDNSEndpointStatus.
func (in *TailnetDNSEndpointStatus) DeepCopy() *TailnetDNSEndpointStatus {
	if in == nil {
		return nil
	}
	out := new(TailnetDNSEndpointStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TailnetNameserver) DeepCopyInto(out *TailnetNameserver) {
	*out = *in
	if in.EndpointRef != nil {
		in, out := &in.EndpointRef, &out.EndpointRef
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TailnetNameserver.
func (in *TailnetNameserver) DeepCopy() *TailnetNameserver {
	if in == nil {
		return nil
	}
	out := new(TailnetNameserver)
	in.DeepCopyInto(out)
	return out
}
